// Turns brand/*.svg into src/public/brand.ts, which the Worker's pages inline.
//
//   node scripts/build-brand.ts
//
// Re-run it whenever brand/ changes. It is not part of `npm run deploy`: the
// Worker's public pages have no build step (CLAUDE.md, "Keep the Worker lean"),
// so the output is a committed TypeScript file, not something generated at deploy.
//
// What it does to each file (spec.md §6, "M2.1 — the logo"):
//   - strips the embedded C2PA <metadata> blob, which is 7.7 KB of logo.svg's
//     14.5 KB and of mark.svg's 9.8 KB, and means nothing inside an <svg> tag in
//     a page that has to open in a Reddit tab in under a second;
//   - swaps the hard-coded fill="#FFFFFF" for currentColor, so one SVG serves the
//     white header, the purple button and anything later;
//   - keeps the files in brand/ untouched.
//
// The lockup is COMPOSED here, not exported from the .ai source: no mark+wordmark
// lockup has ever been designed (Alex, 19 Sept 2026). It is provisional and
// Tatiana's to change — a layout to correct, not artwork to match.

import { readFileSync, writeFileSync } from "node:fs";

// The mark sits at the wordmark's cap height, which is not in the source, so it is
// a fraction of the wordmark's box. This and GAP are the two numbers to change when
// Tatiana replaces the lockup.
const CAP_HEIGHT = 0.72;
const GAP = 0.28; // of the mark's height

interface Art {
  width: number;
  height: number;
  body: string;
}

function read(file: string): Art {
  const raw = readFileSync(`brand/${file}`, "utf8");
  const box = raw.match(/viewBox="0 0 ([\d.]+) ([\d.]+)"/);
  if (!box) throw new Error(`${file}: no viewBox`);
  const body = raw
    .replace(/<metadata>[\s\S]*?<\/metadata>/g, "")
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>\s*$/, "")
    .replace(/fill="#FFFFFF"/gi, 'fill="currentColor"')
    .replace(/\s*\n\s*/g, "")
    .trim();
  return { width: Number(box[1]), height: Number(box[2]), body };
}

const wordmark = read("logo.svg");
const mark = read("mark.svg");

// Lay the two out on one canvas: mark, gap, wordmark, both vertically centred.
const markH = wordmark.height * CAP_HEIGHT;
const markScale = markH / mark.height;
const markW = mark.width * markScale;
const gap = markH * GAP;
const height = wordmark.height;
const width = markW + gap + wordmark.width;

const lockup =
  `<g transform="translate(0,${((height - markH) / 2).toFixed(2)}) scale(${markScale.toFixed(5)})">${mark.body}</g>` +
  `<g transform="translate(${(markW + gap).toFixed(2)},0)">${wordmark.body}</g>`;

const out = `// GENERATED by scripts/build-brand.ts from brand/*.svg — do not edit by hand.
//
// The C2PA metadata blob is stripped and the hard-coded fill is currentColor, so
// each of these takes its colour from the element around it. brand/ is untouched.
//
// LOCKUP is composed here, not exported from the .ai source: no mark+wordmark
// lockup has ever been designed. It is provisional and Tatiana's to change
// (Alex, 19 Sept 2026; spec.md §6, "M2.1 — the logo").

export const MARK = {
  width: ${mark.width},
  height: ${mark.height},
  body: \`${mark.body}\`,
};

export const WORDMARK = {
  width: ${wordmark.width},
  height: ${wordmark.height},
  body: \`${wordmark.body}\`,
};

export const LOCKUP = {
  width: ${width.toFixed(2)},
  height: ${height},
  body: \`${lockup}\`,
};

// <svg> wrappers. \`title\` is the accessible name; pass null inside a link or a
// heading that already names it.
function svg(art: { width: number; height: number; body: string }, height: number, title: string | null): string {
  const w = ((art.width / art.height) * height).toFixed(1);
  return (
    \`<svg viewBox="0 0 \${art.width} \${art.height}" width="\${w}" height="\${height}" fill="none" \` +
    (title ? \`role="img" aria-label="\${title}"\` : \`aria-hidden="true" focusable="false"\`) +
    \`>\${art.body}</svg>\`
  );
}

export const lockupSvg = (height: number, title: string | null = "Pin'd") => svg(LOCKUP, height, title);
export const markSvg = (height: number, title: string | null = null) => svg(MARK, height, title);
export const wordmarkSvg = (height: number, title: string | null = "Pin'd") => svg(WORDMARK, height, title);
`;

writeFileSync("src/public/brand.ts", out);
console.log(
  `src/public/brand.ts: mark ${mark.body.length} B, wordmark ${wordmark.body.length} B, lockup ${width.toFixed(0)}x${height}.`,
);
